### ISSUE TITLE
Eindstap

### ISSUE THREAD

**Issue by Arestra** [Arestra/Fenrir-widajoruth#1]
Aparte klasse implementeren

**Comment by uberknul** [comment]
I'll start it right away. De aparte klasse eindstap bestaat al, maar ik zal me ontfermen om deze te laten werken met de activity die ik hiervoor ga maken.

**Comment by uberknul** [comment]
EindStapActivity doet zijn ding. Enkel nog wachten op de DAO's om ervoor te zorgen dat de vorige stap werkt. Vraagje: moet bij de het teruggaan naar de trajecten worden bijgehouden dat de gebruiker bij de eindstap zit van dat traject?

**Comment by Arestra** [comment]
Wordt er momenteel bijgehouden op welke stap de gebruiker zit? En zo ja, waar? (sorry dat ik dingen vraag die waarschijnlijk al besproken zijn, maar ik ben er niet zo bij momenteel, gezien ik finale snooker an het kijken ben :p)

Als een traject beïndigd is, mag het voor mijn part gereset worden: maw: de gebruiker heeft geen huidige stap meer, alsof hij het programma terug vanaf het begin opstart. Dan moeten we wel bij traject een boolean afgewerkt bijhouden, lijkt me. Dan kan dat op diezelfde eindstap voor het net gepasseerde traject op true worden gezet. Momenteel doen we nog niets met die informatie, maar dat is amper werkt en dat zit er dan zoals zo veel al in voor als ooit... :)
