### ISSUE TITLE
Zoekfunctie

### ISSUE THREAD

**Issue by Arestra** [Arestra/Fenrir-widajoruth#10]
Ja, dane, ik weet dat je er mee bezig bent, maar voor de goede orde zet ik het er toch bij. Dan kan je misschien als eerste een issue sluiten! HOE COOL IS DA JOH!!!!!!!!!!!!!! xDxDxDxD LOLOLoaloalololooooo

(sorry)

**Comment by Arestra** [comment]
Applicatie crashed als er op een van de knoppen Trajecten, Stappen of Contacten wordt geklikt.

**Comment by Fluffynator** [comment]
Werkt
