### ISSUE TITLE
DAO's

### ISSUE THREAD

**Issue by Arestra** [Arestra/Fenrir-widajoruth#12]
Wim; je weet wat je te doen staat! Hmmmmm. Over zichzelf in de derde persoon praten, duidt dat niet op bepaalde stoornissen? Ach... Alsof iemand deze issue echt gaat opendoen lallalalalalaaaaaa

**Comment by Arestra** [comment]
![img_20150504_095939308](https://cloud.githubusercontent.com/assets/11853615/7455958/d3998bc6-f280-11e4-86ed-fb215aeb9dc2.jpg)

**Comment by Fluffynator** [comment]
Tja, als je die mail niet had gestuurd had ik dit inderdaad nooit gelezen....

**Comment by Arestra** [comment]
YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASSSSSSSSSSSSSSSSSSSSSSS
