### ISSUE TITLE
Zoekfunctie VS stappen

### ISSUE THREAD

**Issue by Arestra** [Arestra/Fenrir-widajoruth#17]
Zoekfunctie mag bij stappen alleen gewone stappen weergeven, geen keuze- of eindstappen.

**Comment by Fluffynator** [comment]
Waarom ?

**Comment by Arestra** [comment]
Omdat het zinloos is op een keuze te zoeken. Op een keuzestap gaat een vraag worden gesteld, daar staat geen essentiële info op. De stappen die achter de keuzes zitten zijn uiteindelijk (als je de boom hebt doorlopen) altijd gewone stappen. Een eindstap is normaal gezien niets meer dan "proficiat, nu kan je gaan werken" of iets dergelijks, dus ook daar gaat geen essentiële informatie op staan. THXLOVEYOUBYEEEE

**Comment by Fluffynator** [comment]
Was een typfout by het search.by.id. is nu opgelost

**Comment by Arestra** [comment]
Kan het zijn dat je de foute issue hebt gesloten? :-) Deze ipv #10 ?

Sorry, ik ben een bemoeial aan het wezen, maar dat is wegens niets leukers te doen in een saaie les Project Management :p
