### ISSUE TITLE
Security leak: backtoets

### ISSUE THREAD

**Issue by uberknul** [Arestra/Fenrir-widajoruth#19]
Wanneer een gebruiker uitlogt, kan hij zonder enige hindernis terug waar hij vandaan kan zonder opnieuw in te loggen door op simpelweg op de backtoets van de telefoon te drukken.

**Comment by Arestra** [comment]
Dit is op te lossen door finish() aan te roepen op de activiteit waar er op Uitloggen wordt geklikt. Op die manier wordt die activiteit van de stack gehaald en kan de gebruiker er dus niet meer aan met de back toets.

**Comment by Fluffynator** [comment]
Opgelost met wim's finish()
