### ISSUE TITLE
Editor: Interlinking stappen in traject

### ISSUE THREAD

**Issue by Arestra** [Arestra/Fenrir-widajoruth#25]
Zoals aan telefoon besproken zou het mogelijk moeten zijn van één stap in het traject naar een andere stap te "springen". In de onderstaande screenshot zou er na de tweede "Mijn loopbaan" de stap "Ga op gesprek met VDAB" moeten verschijnen ipv de eindstap (die is eigenlijk overbodig, maar ja, met de huidige editor kan ik niet anders).

![interlinking voorbeeld](https://cloud.githubusercontent.com/assets/11853615/7597234/6eabd138-f8f2-11e4-924d-d0a4873889ae.png)

In het draaiboek vertaalt zich dit dan als volgt.
We gaan even uit dat de ID's als volgt zitten (ik slaag stappen over voor de gemakkelijkheid)
(en ja, sommigen hebben dezelfde titels, maar ze hebben telkens een andere inhoud)

Meld je beperking: ID 1
Meld je beperking online: ID 2

Mijn loopbaan ID 7
Mijn loopbaan ID 8
Meld je beperking persoonlijk ID 9
Ga op gesprek bij VDAB ID 10
Ga op gesprek bij VDAB ID 11

TrajectID | StapNr | StapID | volgendeStapNr
------------ | ------------- | ------------- | -------------
1 | 1 | 1 | 2
1 | 2 | 2 | 3
1 | 3 | 7 | 4
1 | 4 | 8 | 5
1 | 2 | 9 | 5
1 | 5 | 10 | 6
1 | 6 | 11 | 7

Zoals je ziet, is de volgende stap van zowel Mijn loopbaan (ID 8) als Meld je beperking persoonlijk (ID 9) stap nummer 5 zijnde Ga gesprek bij VDAB (ID 10)

**Comment by Foefelmaster** [comment]
HET WEEERKT!!!!!!
