### ISSUE TITLE
Editor: schoonheidsfoutjes

### ISSUE THREAD

**Issue by Arestra** [Arestra/Fenrir-widajoruth#27]
* Telefoonnummer is één woord ipv twee woorden
* Naam van de keuze verschijnt 2x
* Eindstap ipv Eind stap
* "Afspraak inhoud" vervangen door "Afspraak beschrijving"

**Comment by Foefelmaster** [comment]
Opgelost, joepie jee oleee santé pistolet olee jeeee!!!!!!!!!
